export interface AzureModel {
  id: string
  name: string
  tokenLimit: number
  enabled: boolean
  azureDeploymentModelName: string
  azureDeploymentID?: string // Each deployment has a `model` and  `id`. The deployment ID is needed for making chat requests.
  default?: boolean
  temperature?: number
}

export enum AzureModelID {
  o3 = 'o3',
  o4_mini = 'o4-mini',
  GPT_4o_mini = 'gpt-4o-mini-2024-07-18',
  GPT_4o = 'gpt-4o-2024-08-06',
  GPT_4_1 = 'gpt-4.1',
  GPT_4_1_mini = 'gpt-4.1-mini',
  GPT_4_1_nano = 'gpt-4.1-nano',
  GPT_5_5 = 'gpt-5.5',
  GPT_5_4 = 'gpt-5.4',
  GPT_5_4_pro = 'gpt-5.4-pro',
  GPT_5_4_mini = 'gpt-5.4-mini',
  GPT_5_4_nano = 'gpt-5.4-nano',
  GPT_5_3_chat_latest = 'gpt-5.3-chat-latest',
  GPT_5_2 = 'gpt-5.2',
  GPT_5_2_codex = 'gpt-5.2-codex',
  GPT_5_1 = 'gpt-5.1',
  GPT_5_1_chat_latest = 'gpt-5.1-chat-latest',
  GPT_5_1_codex = 'gpt-5.1-codex',
  GPT_5_1_codex_mini = 'gpt-5.1-codex-mini',
  GPT_5 = 'gpt-5',
  GPT_5_mini = 'gpt-5-mini',
  GPT_5_nano = 'gpt-5-nano',
  GPT_5_thinking = 'gpt-5-thinking',
}

export enum AzureDeploymentModelName {
  o3 = 'o3',
  o4_mini = 'o4-mini',
  GPT_4o_mini = 'gpt-4o-mini',
  GPT_4o = 'gpt-4o',
  GPT_4_1 = 'gpt-4.1',
  GPT_4_1_mini = 'gpt-4.1-mini',
  GPT_4_1_nano = 'gpt-4.1-nano',
  GPT_5_5 = 'gpt-5.5',
  GPT_5_4 = 'gpt-5.4',
  GPT_5_4_pro = 'gpt-5.4-pro',
  GPT_5_4_mini = 'gpt-5.4-mini',
  GPT_5_4_nano = 'gpt-5.4-nano',
  GPT_5_3_chat_latest = 'gpt-5.3-chat-latest',
  GPT_5_2 = 'gpt-5.2',
  GPT_5_2_codex = 'gpt-5.2-codex',
  GPT_5_1 = 'gpt-5.1',
  GPT_5_1_chat_latest = 'gpt-5.1-chat-latest',
  GPT_5_1_codex = 'gpt-5.1-codex',
  GPT_5_1_codex_mini = 'gpt-5.1-codex-mini',
  GPT_5 = 'gpt-5',
  GPT_5_mini = 'gpt-5-mini',
  GPT_5_nano = 'gpt-5-nano',
  GPT_5_thinking = 'gpt-5-thinking',
}

export const AzureModels: Record<AzureModelID, AzureModel> = {
  [AzureModelID.o3]: {
    id: AzureModelID.o3,
    name: 'o3 (Reasoning)',
    azureDeploymentModelName: AzureDeploymentModelName.o3,
    tokenLimit: 200000,
    enabled: true,
  },
  [AzureModelID.o4_mini]: {
    id: AzureModelID.o4_mini,
    name: 'o4-mini (Reasoning)',
    azureDeploymentModelName: AzureDeploymentModelName.o4_mini,
    tokenLimit: 200000,
    enabled: true,
  },
  [AzureModelID.GPT_4o]: {
    id: AzureModelID.GPT_4o,
    name: 'GPT-4o',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_4o,
    tokenLimit: 128000,
    enabled: true,
  },
  [AzureModelID.GPT_4o_mini]: {
    id: AzureModelID.GPT_4o_mini,
    name: 'GPT-4o mini',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_4o_mini,
    tokenLimit: 128000,
    enabled: true,
  },
  [AzureModelID.GPT_4_1]: {
    id: AzureModelID.GPT_4_1,
    name: 'GPT-4.1',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_4_1,
    tokenLimit: 1047576,
    enabled: true,
  },
  [AzureModelID.GPT_4_1_mini]: {
    id: AzureModelID.GPT_4_1_mini,
    name: 'GPT-4.1 Mini',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_4_1_mini,
    tokenLimit: 1047576,
    enabled: true,
  },
  [AzureModelID.GPT_4_1_nano]: {
    id: AzureModelID.GPT_4_1_nano,
    name: 'GPT-4.1 Nano',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_4_1_nano,
    tokenLimit: 1047576,
    enabled: true,
  },
  [AzureModelID.GPT_5_5]: {
    id: AzureModelID.GPT_5_5,
    name: 'GPT-5.5',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_5,
    tokenLimit: 1050000,
    enabled: true,
  },
  [AzureModelID.GPT_5_4]: {
    id: AzureModelID.GPT_5_4,
    name: 'GPT-5.4',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_4,
    tokenLimit: 1050000,
    enabled: true,
  },
  [AzureModelID.GPT_5_4_pro]: {
    id: AzureModelID.GPT_5_4_pro,
    name: 'GPT-5.4 Pro',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_4_pro,
    tokenLimit: 1050000,
    enabled: true,
  },
  [AzureModelID.GPT_5_4_mini]: {
    id: AzureModelID.GPT_5_4_mini,
    name: 'GPT-5.4 Mini',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_4_mini,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_4_nano]: {
    id: AzureModelID.GPT_5_4_nano,
    name: 'GPT-5.4 Nano',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_4_nano,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_3_chat_latest]: {
    id: AzureModelID.GPT_5_3_chat_latest,
    name: 'GPT-5.3 Chat',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_3_chat_latest,
    tokenLimit: 128000,
    enabled: true,
  },
  [AzureModelID.GPT_5_2]: {
    id: AzureModelID.GPT_5_2,
    name: 'GPT-5.2',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_2,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_2_codex]: {
    id: AzureModelID.GPT_5_2_codex,
    name: 'GPT-5.2 Codex',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_2_codex,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_1]: {
    id: AzureModelID.GPT_5_1,
    name: 'GPT-5.1',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_1,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_1_chat_latest]: {
    id: AzureModelID.GPT_5_1_chat_latest,
    name: 'GPT-5.1 Chat',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_1_chat_latest,
    tokenLimit: 128000,
    enabled: true,
  },
  [AzureModelID.GPT_5_1_codex]: {
    id: AzureModelID.GPT_5_1_codex,
    name: 'GPT-5.1 Codex',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_1_codex,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_1_codex_mini]: {
    id: AzureModelID.GPT_5_1_codex_mini,
    name: 'GPT-5.1 Codex Mini',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_1_codex_mini,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5]: {
    id: AzureModelID.GPT_5,
    name: 'GPT-5',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_mini]: {
    id: AzureModelID.GPT_5_mini,
    name: 'GPT-5 Mini',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_mini,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_nano]: {
    id: AzureModelID.GPT_5_nano,
    name: 'GPT-5 Nano',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_nano,
    tokenLimit: 400000,
    enabled: true,
  },
  [AzureModelID.GPT_5_thinking]: {
    id: AzureModelID.GPT_5_thinking,
    name: 'GPT-5 Thinking',
    azureDeploymentModelName: AzureDeploymentModelName.GPT_5_thinking,
    tokenLimit: 400000,
    enabled: true,
  },
}
