-- provision_external_pgvector_store.sql
--
-- Generic, idempotent provisioning script for an EXTERNAL pgvector document store
-- used by the illinois-chat / uiuc-chat ingest pipeline.
--
-- Creates ONLY the ingest + pgvector core needed for a project's external data
-- store: the document tables, the doc-group tables, the in-progress/failed
-- tracking tables, the pgvector `embeddings` table (VECTOR 4096), and the ingest
-- RPCs/triggers. It deliberately omits host-side concerns (projects,
-- project_external_connections, audit log) and all chat/analytics tables.
--
-- Project-agnostic (no hard-coded course/project name) and safe to re-run.
-- Target: PostgreSQL >= 15 with the pgvector extension available. Apply via
-- psql (or your provider's SQL runner, e.g. Supabase's apply_migration).
--
-- Source of truth: apps/frontend/src/db/schema.ts (documents/doc-group/
-- embeddings subset) + apps/frontend/src/db/migrations/0001_custom_functions.sql.
-- See docs/external-connections-setup.md for the full setup walkthrough.
--
-- This script provisions a NEW store and must always reflect the latest schema.
-- Bringing an ALREADY-provisioned store up to date is the job of the ordered
-- scripts in infra/db/external-migrations/ — any document-related change made
-- here needs a matching numbered file there. See that directory's README.

BEGIN;

-- ============================================================================
-- Extension
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- Tables
-- ============================================================================

-- documents: one row per ingested document
CREATE TABLE IF NOT EXISTS public.documents (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamp with time zone DEFAULT now(),
  s3_path           text,
  readable_filename text,
  course_name       text,
  url               text,
  contexts          jsonb,
  base_url          text
);
CREATE INDEX IF NOT EXISTS documents_course_name_idx ON public.documents USING hash (course_name);
CREATE INDEX IF NOT EXISTS documents_created_at_idx  ON public.documents USING btree (created_at);

-- doc_groups: logical grouping of documents (unique per name+course)
CREATE TABLE IF NOT EXISTS public.doc_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  course_name text NOT NULL,
  created_at  timestamp with time zone NOT NULL DEFAULT now(),
  enabled     boolean NOT NULL DEFAULT true,
  private     boolean NOT NULL DEFAULT true,
  doc_count   bigint DEFAULT 0,
  CONSTRAINT doc_groups_name_course_unique UNIQUE (name, course_name)
);

-- documents_doc_groups: many-to-many junction (composite PK)
-- ON DELETE CASCADE on document_id keeps doc_groups.doc_count in sync via
-- trg_update_doc_count_after_insert when documents are deleted.
CREATE TABLE IF NOT EXISTS public.documents_doc_groups (
  document_id  bigint NOT NULL,
  doc_group_id bigint NOT NULL,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT documents_doc_groups_pkey PRIMARY KEY (document_id, doc_group_id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'documents_doc_groups_document_id_documents_id_fk'
  ) THEN
    -- Disable count trigger while cleaning orphans so already-drifted
    -- doc_count values are not driven further negative, then recompute.
    IF EXISTS (
      SELECT 1 FROM pg_trigger
      WHERE tgname = 'trg_update_doc_count_after_insert'
        AND tgrelid = 'public.documents_doc_groups'::regclass
    ) THEN
      ALTER TABLE public.documents_doc_groups
        DISABLE TRIGGER trg_update_doc_count_after_insert;
    END IF;

    DELETE FROM public.documents_doc_groups ddg
    WHERE NOT EXISTS (
      SELECT 1 FROM public.documents d WHERE d.id = ddg.document_id
    );
    DELETE FROM public.documents_doc_groups ddg
    WHERE NOT EXISTS (
      SELECT 1 FROM public.doc_groups dg WHERE dg.id = ddg.doc_group_id
    );
    UPDATE public.doc_groups dg
    SET doc_count = (
      SELECT COUNT(*) FROM public.documents_doc_groups ddg
      WHERE ddg.doc_group_id = dg.id
    );

    IF EXISTS (
      SELECT 1 FROM pg_trigger
      WHERE tgname = 'trg_update_doc_count_after_insert'
        AND tgrelid = 'public.documents_doc_groups'::regclass
    ) THEN
      ALTER TABLE public.documents_doc_groups
        ENABLE TRIGGER trg_update_doc_count_after_insert;
    END IF;

    ALTER TABLE public.documents_doc_groups
      ADD CONSTRAINT documents_doc_groups_document_id_documents_id_fk
      FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'documents_doc_groups_doc_group_id_doc_groups_id_fk'
  ) THEN
    ALTER TABLE public.documents_doc_groups
      ADD CONSTRAINT documents_doc_groups_doc_group_id_doc_groups_id_fk
      FOREIGN KEY (doc_group_id) REFERENCES public.doc_groups(id) ON DELETE CASCADE;
  END IF;
END $$;

-- documents_in_progress: ingest job tracking (beam_task_id == queue job_id)
CREATE TABLE IF NOT EXISTS public.documents_in_progress (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamp with time zone NOT NULL DEFAULT now(),
  s3_path           text,
  readable_filename text,
  course_name       text,
  url               text,
  contexts          jsonb,
  base_url          text,
  doc_groups        text,
  error             text,
  beam_task_id      text
);

-- documents_failed: terminal failures
CREATE TABLE IF NOT EXISTS public.documents_failed (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamp with time zone NOT NULL DEFAULT now(),
  s3_path           text,
  readable_filename text,
  course_name       text,
  url               text,
  contexts          jsonb,
  base_url          text,
  doc_groups        text,
  error             text
);

-- embeddings: pgvector store (VECTOR 4096; mirrors Qdrant "illinois-chat-qwen")
CREATE TABLE IF NOT EXISTS public.embeddings (
  id                bigserial PRIMARY KEY,
  qdrant_id         uuid UNIQUE,
  embedding         vector(4096) NOT NULL,
  page_content      text,
  course_name       text,
  s3_path           text,
  readable_filename text,
  url               text,
  base_url          text,
  doc_groups        jsonb DEFAULT '[]'::jsonb,
  chunk_index       integer,
  pagenumber        text,
  "timestamp"       text,
  conversation_id   text,
  metadata          jsonb DEFAULT '{}'::jsonb,
  created_at        timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at        timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS embeddings_course_name_idx     ON public.embeddings (course_name);
CREATE INDEX IF NOT EXISTS embeddings_s3_path_idx         ON public.embeddings (s3_path);
CREATE INDEX IF NOT EXISTS embeddings_conversation_id_idx ON public.embeddings (conversation_id)
  WHERE conversation_id IS NOT NULL AND conversation_id != '';
CREATE INDEX IF NOT EXISTS embeddings_doc_groups_idx      ON public.embeddings USING gin (doc_groups);
CREATE INDEX IF NOT EXISTS embeddings_metadata_idx        ON public.embeddings USING gin (metadata);

-- ANN index for vector search. The frontend (uiuc-chat-frontend
-- src/db/vectorSearch.ts) searches on the FIRST 1536 dims of the 4096-dim
-- embedding — pgvector cannot index `vector` columns above 2000 dims, and
-- Qwen3-Embedding is Matryoshka-trained so truncation preserves ranking
-- quality. The index expression below must stay byte-identical to that
-- query's ORDER BY expression or the planner will fall back to a full
-- sequential scan.
--
-- NOTE: fine to run inline here on a fresh (EMPTY) database — the build is
-- instant with no rows. Adding it to an ALREADY-POPULATED table is the fiddly
-- case; run it separately, outside a transaction, as:
--
--   SET maintenance_work_mem = '32GB';        -- MUST exceed the graph size
--   SET max_parallel_maintenance_workers = 0; -- MUST be 0; see trap 2
--   CREATE INDEX CONCURRENTLY ...             -- (same definition as below)
--
-- Two traps, both hit for real while indexing 3.07M vectors on 2026-07-17:
--
--  1. maintenance_work_mem must exceed the in-memory graph (~25 GB for 3M
--     vectors x 1536 dims; roughly 1.4x the raw vector bytes). If it does not
--     fit, the build spills to disk and decays badly — on a Supabase Medium
--     (4 GB RAM, 1 GB budget) it fell from ~277 to ~17 tuples/s, a ~2-day ETA.
--     Scale compute UP for the build only, then scale back down; steady-state
--     search does not need the big instance. 4XL (64 GB) fit a 32 GB budget.
--
--  2. Do NOT use a parallel build with a large maintenance_work_mem. pgvector
--     puts the graph in shared memory (/dev/shm, capped well below total RAM),
--     so a parallel build fails outright with
--       ERROR: could not resize shared memory segment ... No space left on device
--     A SERIAL build (max_parallel_maintenance_workers = 0) allocates in private
--     process memory instead and can use the full free RAM. Serial + fully
--     in-memory sustained ~985 tuples/s with no decay (~1 h for 3.07M), versus
--     the ~2 days it was heading for while spilling.
--
-- Building it takes a write lock unless CONCURRENTLY is used. Expect the index
-- to be roughly as large as the vectors it covers (21 GB for 3.07M x 1536).
CREATE INDEX IF NOT EXISTS embeddings_embedding_1536_hnsw_idx
  ON public.embeddings USING hnsw
  ((subvector(embedding, 1, 1536)::vector(1536)) vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ============================================================================
-- Functions
-- ============================================================================

-- Touch updated_at on embeddings UPDATE
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;$$;

-- Maintain doc_groups.doc_count on junction INSERT/DELETE
CREATE OR REPLACE FUNCTION public.update_doc_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE doc_groups SET doc_count = doc_count + 1 WHERE id = NEW.doc_group_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE doc_groups SET doc_count = doc_count - 1 WHERE id = OLD.doc_group_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;$$;

-- Worker RPC: associate an existing document (matched by s3_path) with groups
CREATE OR REPLACE FUNCTION public.add_document_to_group(p_course_name text, p_s3_path text, p_url text, p_readable_filename text, p_doc_groups text[]) RETURNS boolean
    LANGUAGE plpgsql
    AS $$DECLARE
    v_document_id bigint;
    v_doc_group_id bigint;
    v_success boolean := true;
    p_doc_group text;
BEGIN
    -- Ensure the document exists
    SELECT id INTO v_document_id FROM public.documents WHERE course_name = p_course_name AND (
    (s3_path <> '' AND s3_path IS NOT NULL AND s3_path = p_s3_path)
);

    raise log 'id of document: %', v_document_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document does not exist';
    END IF;

    -- Loop through document groups
    FOREACH p_doc_group IN ARRAY p_doc_groups
    LOOP
        -- Upsert document group, assuming 'name' and 'course_name' can uniquely identify a row
        INSERT INTO public.doc_groups(name, course_name)
        VALUES (p_doc_group, p_course_name)
        ON CONFLICT (name, course_name) DO UPDATE
        SET name = EXCLUDED.name
        RETURNING id INTO v_doc_group_id;

        raise log 'id of document group: %', v_doc_group_id;

        -- Upsert the association in documents_doc_groups.
        -- Concurrent delete between SELECT and INSERT: no-op (do not fail ingest).
        BEGIN
            INSERT INTO public.documents_doc_groups(document_id, doc_group_id)
            VALUES (v_document_id, v_doc_group_id)
            ON CONFLICT (document_id, doc_group_id) DO NOTHING;
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE LOG 'add_document_to_group: skipping FK violation for document_id=% doc_group_id=%',
                    v_document_id, v_doc_group_id;
        END;

        raise log 'completed for %',v_doc_group_id;
    END LOOP;

    raise log 'completed for %',v_document_id;
    RETURN v_success;
EXCEPTION
    WHEN OTHERS THEN
        v_success := false;
        RAISE;
        RETURN v_success;
END;$$;

-- Worker RPC: associate an existing document (matched by s3_path OR url) with groups
CREATE OR REPLACE FUNCTION public.add_document_to_group_url(p_course_name text, p_s3_path text, p_url text, p_readable_filename text, p_doc_groups text[]) RETURNS boolean
    LANGUAGE plpgsql
    AS $$DECLARE
    v_document_id bigint;
    v_doc_group_id bigint;
    v_success boolean := true;
    p_doc_group text;
BEGIN
    -- Ensure the document exists
    SELECT id INTO v_document_id FROM public.documents WHERE course_name = p_course_name AND (
    (s3_path <> '' AND s3_path IS NOT NULL AND s3_path = p_s3_path) OR
    (url = p_url)
);

    raise log 'id of document: %', v_document_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document does not exist';
    END IF;

    -- Loop through document groups
    FOREACH p_doc_group IN ARRAY p_doc_groups
    LOOP
        -- Upsert document group, assuming 'name' and 'course_name' can uniquely identify a row
        INSERT INTO public.doc_groups(name, course_name)
        VALUES (p_doc_group, p_course_name)
        ON CONFLICT (name, course_name) DO UPDATE
        SET name = EXCLUDED.name
        RETURNING id INTO v_doc_group_id;

        raise log 'id of document group: %', v_doc_group_id;

        -- Upsert the association in documents_doc_groups.
        -- Concurrent delete between SELECT and INSERT: no-op (do not fail ingest).
        BEGIN
            INSERT INTO public.documents_doc_groups(document_id, doc_group_id)
            VALUES (v_document_id, v_doc_group_id)
            ON CONFLICT (document_id, doc_group_id) DO NOTHING;
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE LOG 'add_document_to_group_url: skipping FK violation for document_id=% doc_group_id=%',
                    v_document_id, v_doc_group_id;
        END;

        raise log 'completed for %',v_doc_group_id;
    END LOOP;

    raise log 'completed for %',v_document_id;
    RETURN v_success;
EXCEPTION
    WHEN OTHERS THEN
        v_success := false;
        RAISE;
        RETURN v_success;
END;$$;

-- Remove a document from a group; delete the group if it becomes empty
CREATE OR REPLACE FUNCTION public.remove_document_from_group(p_course_name text, p_s3_path text, p_url text, p_doc_group text) RETURNS void
    LANGUAGE plpgsql
    AS $$DECLARE
    v_document_id bigint;
    v_doc_group_id bigint;
    v_doc_count bigint;
BEGIN
    -- Check if the document exists
    SELECT id INTO v_document_id FROM public.documents WHERE course_name = p_course_name AND (
    (s3_path <> '' AND s3_path IS NOT NULL AND s3_path = p_s3_path) OR
    (url = p_url)
);
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document does not exist';
    END IF;

    -- Check if the document group exists
    SELECT id, doc_count INTO v_doc_group_id, v_doc_count
    FROM public.doc_groups
    WHERE name = p_doc_group AND course_name = p_course_name;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document group does not exist';
    END IF;

    -- Delete the association
    DELETE FROM public.documents_doc_groups
    WHERE document_id = v_document_id AND doc_group_id = v_doc_group_id;

    -- If the doc_count becomes 0, delete the doc_group
    IF v_doc_count = 1 THEN
        DELETE FROM public.doc_groups
        WHERE id = v_doc_group_id;
    END IF;
END;$$;

-- ============================================================================
-- Triggers (idempotent)
-- ============================================================================

DROP TRIGGER IF EXISTS update_embeddings_updated_at ON public.embeddings;
CREATE TRIGGER update_embeddings_updated_at
    BEFORE UPDATE ON public.embeddings
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_update_doc_count_after_insert') THEN
    CREATE TRIGGER trg_update_doc_count_after_insert
      AFTER INSERT OR DELETE ON public.documents_doc_groups
      FOR EACH ROW EXECUTE FUNCTION public.update_doc_count();
  END IF;
END;
$$ LANGUAGE plpgsql;

COMMIT;
