#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

COMPOSE=(docker compose --project-directory . -f infra/docker/docker-compose.dev.yaml -f infra/docker/docker-compose.sim.yaml)
QDRANT_COLLECTION_NAME="${QDRANT_COLLECTION_NAME:-illinois_chat}"
QDRANT_VECTOR_SIZE="${QDRANT_VECTOR_SIZE:-4096}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
	echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
	echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
	echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
	echo -e "${RED}[ERROR]${NC} $1"
}

append_env_if_missing() {
	local file="$1"
	local key="$2"
	local value="$3"

	if ! grep -q "^${key}=" "$file"; then
		printf "%s=%s\n" "$key" "$value" >>"$file"
	fi
}

ensure_env_file() {
	local file="$1"
	local title="$2"

	mkdir -p "$(dirname "$file")"
	if [ ! -f "$file" ]; then
		cat >"$file" <<EOF
# ${title}
# Generated by infra/scripts/start-dev.sh.
# Existing values are preserved; reruns only append missing keys.

EOF
		print_success "Created $file"
	fi
}

ensure_local_app_envs() {
	print_status "Ensuring app-local .env files exist..."

	local postgres_password="${POSTGRES_PASSWORD:-password}"
	local postgres_database="${POSTGRES_DATABASE:-postgres}"
	local postgres_user="${POSTGRES_USER:-${POSTGRES_USERNAME:-postgres}}"
	local redis_password="${INGEST_REDIS_PASSWORD:-your-strong-password-here}"
	local rabbitmq_user="${RABBITMQ_USER:-guest}"
	local rabbitmq_pass="${RABBITMQ_PASS:-guest}"
	local qdrant_api_key="${QDRANT_API_KEY:-your-strong-key-here}"
	local qdrant_collection="${QDRANT_COLLECTION_NAME:-illinois-chat-qwen}"
	local aws_access_key="${AWS_ACCESS_KEY_ID:-minioadmin}"
	local aws_secret_key="${AWS_SECRET_ACCESS_KEY:-minioadmin}"
	local s3_bucket="${S3_BUCKET_NAME:-uiuc-chat}"
	local aws_region="${AWS_REGION:-us-east-1}"
	local keycloak_admin="${KEYCLOAK_ADMIN_USERNAME:-admin}"
	local keycloak_password="${KEYCLOAK_ADMIN_PASSWORD:-admin}"

	local backend_env="apps/backend/.env"
	ensure_env_file "$backend_env" "Backend and worker local development env"
	append_env_if_missing "$backend_env" "POSTGRES_ENDPOINT" "localhost"
	append_env_if_missing "$backend_env" "POSTGRES_PORT" "5432"
	append_env_if_missing "$backend_env" "POSTGRES_DATABASE" "$postgres_database"
	append_env_if_missing "$backend_env" "POSTGRES_USER" "$postgres_user"
	append_env_if_missing "$backend_env" "POSTGRES_USERNAME" "$postgres_user"
	append_env_if_missing "$backend_env" "POSTGRES_PASSWORD" "$postgres_password"
	append_env_if_missing "$backend_env" "POSTGRES_SSL" "false"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_ENDPOINT" "localhost"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_PORT" "5433"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_DATABASE" "$postgres_database"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_USERNAME" "$postgres_user"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_PASSWORD" "$postgres_password"
	append_env_if_missing "$backend_env" "KEYCLOAK_DB_SSL" "false"
	append_env_if_missing "$backend_env" "RABBITMQ_URL" "amqp://${rabbitmq_user}:${rabbitmq_pass}@localhost:5672"
	append_env_if_missing "$backend_env" "REDIS_URL" "redis://default:${redis_password}@localhost:6379"
	append_env_if_missing "$backend_env" "KV_REST_API_TOKEN" "$redis_password"
	append_env_if_missing "$backend_env" "QDRANT_COLLECTION_NAME" "$qdrant_collection"
	append_env_if_missing "$backend_env" "QDRANT_URL" "http://localhost:6333"
	append_env_if_missing "$backend_env" "QDRANT_API_KEY" "$qdrant_api_key"
	append_env_if_missing "$backend_env" "LOCAL_MINIO" "true"
	append_env_if_missing "$backend_env" "MINIO_URL" "http://localhost:10000"
	append_env_if_missing "$backend_env" "MINIO_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$backend_env" "MINIO_PUBLIC_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$backend_env" "AWS_REGION" "$aws_region"
	append_env_if_missing "$backend_env" "AWS_ACCESS_KEY_ID" "$aws_access_key"
	append_env_if_missing "$backend_env" "AWS_SECRET_ACCESS_KEY" "$aws_secret_key"
	append_env_if_missing "$backend_env" "S3_BUCKET_NAME" "$s3_bucket"
	append_env_if_missing "$backend_env" "RAILWAY_URL" "http://localhost:8000"
	append_env_if_missing "$backend_env" "INGEST_URL" "http://localhost:8000/ingest"
	append_env_if_missing "$backend_env" "KEYCLOAK_URL" "http://localhost:8080/"
	append_env_if_missing "$backend_env" "KEYCLOAK_ADMIN_USERNAME" "$keycloak_admin"
	append_env_if_missing "$backend_env" "KEYCLOAK_ADMIN_PASSWORD" "$keycloak_password"
	append_env_if_missing "$backend_env" "NEXT_PUBLIC_KEYCLOAK_URL" "http://localhost:8080/"
	append_env_if_missing "$backend_env" "NEXT_PUBLIC_KEYCLOAK_REALM" "illinois_chat_realm"
	append_env_if_missing "$backend_env" "NEXT_PUBLIC_KEYCLOAK_CLIENT_ID" "illinois_chat"
	append_env_if_missing "$backend_env" "EMBEDDING_MODEL" ""
	append_env_if_missing "$backend_env" "EMBEDDING_API_BASE" ""
	append_env_if_missing "$backend_env" "NCSA_HOSTED_API_KEY" ""
	append_env_if_missing "$backend_env" "NCSA_HOSTED_VLM_BASE_URL" ""
	append_env_if_missing "$backend_env" "OLLAMA_SERVER_URL" ""
	append_env_if_missing "$backend_env" "OPENAI_API_KEY" ""
	append_env_if_missing "$backend_env" "VLADS_OPENAI_KEY" ""
	append_env_if_missing "$backend_env" "POSTHOG_API_KEY" ""
	append_env_if_missing "$backend_env" "NOMIC_API_KEY" ""
	append_env_if_missing "$backend_env" "SENTRY_DSN" ""

	local frontend_env="apps/frontend/.env"
	ensure_env_file "$frontend_env" "Frontend local development env"
	append_env_if_missing "$frontend_env" "PORT" "3000"
	append_env_if_missing "$frontend_env" "RAILWAY_URL" "http://localhost:8000"
	append_env_if_missing "$frontend_env" "INGEST_URL" "http://localhost:8000/ingest"
	append_env_if_missing "$frontend_env" "CRAWLEE_API_URL" "http://localhost:3345/crawl"
	append_env_if_missing "$frontend_env" "REDIS_URL" "redis://default:${redis_password}@localhost:6379"
	append_env_if_missing "$frontend_env" "POSTGRES_ENDPOINT" "localhost"
	append_env_if_missing "$frontend_env" "POSTGRES_PORT" "5432"
	append_env_if_missing "$frontend_env" "POSTGRES_DATABASE" "$postgres_database"
	append_env_if_missing "$frontend_env" "POSTGRES_USERNAME" "$postgres_user"
	append_env_if_missing "$frontend_env" "POSTGRES_PASSWORD" "$postgres_password"
	append_env_if_missing "$frontend_env" "POSTGRES_SSL" "false"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_ENDPOINT" "localhost"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_PORT" "5433"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_DATABASE" "$postgres_database"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_USERNAME" "$postgres_user"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_PASSWORD" "$postgres_password"
	append_env_if_missing "$frontend_env" "KEYCLOAK_DB_SSL" "false"
	append_env_if_missing "$frontend_env" "LOCAL_MINIO" "true"
	append_env_if_missing "$frontend_env" "AWS_REGION" "$aws_region"
	append_env_if_missing "$frontend_env" "AWS_KEY" "$aws_access_key"
	append_env_if_missing "$frontend_env" "AWS_SECRET" "$aws_secret_key"
	append_env_if_missing "$frontend_env" "AWS_ACCESS_KEY_ID" "$aws_access_key"
	append_env_if_missing "$frontend_env" "AWS_SECRET_ACCESS_KEY" "$aws_secret_key"
	append_env_if_missing "$frontend_env" "S3_BUCKET_NAME" "$s3_bucket"
	append_env_if_missing "$frontend_env" "MINIO_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$frontend_env" "MINIO_PUBLIC_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_S3_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$frontend_env" "QDRANT_COLLECTION_NAME" "$qdrant_collection"
	append_env_if_missing "$frontend_env" "QDRANT_URL" "http://localhost:6333"
	append_env_if_missing "$frontend_env" "QDRANT_API_KEY" "$qdrant_api_key"
	append_env_if_missing "$frontend_env" "KEYCLOAK_URL" "http://localhost:8080/"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_KEYCLOAK_URL" "http://localhost:8080/"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_KEYCLOAK_REALM" "illinois_chat_realm"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_KEYCLOAK_CLIENT_ID" "illinois_chat"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_USE_ILLINOIS_CHAT_CONFIG" "True"
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_SIGNING_KEY" ""
	append_env_if_missing "$frontend_env" "EMBEDDING_MODEL" ""
	append_env_if_missing "$frontend_env" "EMBEDDING_API_BASE" ""
	append_env_if_missing "$frontend_env" "NCSA_HOSTED_API_KEY" ""
	append_env_if_missing "$frontend_env" "NCSA_HOSTED_VLM_BASE_URL" ""
	append_env_if_missing "$frontend_env" "OLLAMA_SERVER_URL" ""
	append_env_if_missing "$frontend_env" "OPENAI_API_KEY" ""
	append_env_if_missing "$frontend_env" "VLADS_OPENAI_KEY" ""
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_POSTHOG_HOST" ""
	append_env_if_missing "$frontend_env" "NEXT_PUBLIC_POSTHOG_KEY" ""
	append_env_if_missing "$frontend_env" "POSTHOG_API_KEY" ""

	local crawlee_env="apps/crawlee/.env"
	ensure_env_file "$crawlee_env" "Crawlee local development env"
	append_env_if_missing "$crawlee_env" "PORT" "3345"
	append_env_if_missing "$crawlee_env" "INGEST_URL" "http://localhost:8000/ingest"
	append_env_if_missing "$crawlee_env" "LOCAL_MINIO" "true"
	append_env_if_missing "$crawlee_env" "AWS_REGION" "$aws_region"
	append_env_if_missing "$crawlee_env" "AWS_KEY" "$aws_access_key"
	append_env_if_missing "$crawlee_env" "AWS_SECRET" "$aws_secret_key"
	append_env_if_missing "$crawlee_env" "AWS_ACCESS_KEY_ID" "$aws_access_key"
	append_env_if_missing "$crawlee_env" "AWS_SECRET_ACCESS_KEY" "$aws_secret_key"
	append_env_if_missing "$crawlee_env" "S3_BUCKET_NAME" "$s3_bucket"
	append_env_if_missing "$crawlee_env" "MINIO_ENDPOINT" "http://localhost:10000"
	append_env_if_missing "$crawlee_env" "NO_CRAWL" ""
	append_env_if_missing "$crawlee_env" "PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH" ""
	append_env_if_missing "$crawlee_env" "OPENAI_API_KEY" ""
	append_env_if_missing "$crawlee_env" "NCSA_HOSTED_API_KEY" ""
	append_env_if_missing "$crawlee_env" "EMBEDDING_API_BASE" ""
	append_env_if_missing "$crawlee_env" "EMBEDDING_MODEL" ""

	print_success "App-local .env files are ready."
}

# Function to show usage
show_usage() {
	echo "Usage: $0 [OPTIONS]"
	echo ""
	echo "Options:"
	echo "  --clean    Clear existing containers, volumes, and data before startup"
	echo "  --help     Show this help message"
	echo ""
	echo "Examples:"
	echo "  $0              # Start development infrastructure"
	echo "  $0 --clean      # Clear everything and start fresh"
}

# Parse command line arguments
CLEAN_MODE=false

while [[ $# -gt 0 ]]; do
	case $1 in
	--clean)
		CLEAN_MODE=true
		shift
		;;
	--help | -h)
		show_usage
		exit 0
		;;
	*)
		print_error "Unknown option: $1"
		show_usage
		exit 1
		;;
	esac
done

echo "Starting UIUC.chat Development Environment"
echo "=================================================="

# Clean mode: Clear existing containers and volumes
if [ "$CLEAN_MODE" = true ]; then
	print_warning "CLEAN MODE: Clearing existing containers, volumes, and data..."

	# Stop and remove containers
	print_status "Stopping and removing existing containers..."
	"${COMPOSE[@]}" down -v --remove-orphans 2>/dev/null || true

	print_success "Cleanup completed!"
	echo ""
fi

# Check if .env file exists
if [ ! -f .env ]; then
	print_warning ".env file not found. Creating from template..."
	if [ -f .env.template ]; then
		cp .env.template .env
		print_success "Created .env from template"
	else
		print_error ".env.template not found. Creating default .env file..."
		cat >.env <<'EOF'
# Database Configuration
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_ENDPOINT=localhost
POSTGRES_PORT=5432
POSTGRES_DATABASE=postgres

# Qdrant Configuration
QDRANT_URL=http://localhost:6333
QDRANT_API_KEY=your-strong-key-here

# Redis Configuration
INGEST_REDIS_PASSWORD=password

# MinIO Configuration
AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=minioadmin
DOCKER_INTERNAL_MINIO_API_PORT=10000
DOCKER_INTERNAL_MINIO_DASHBOARD_PORT=9001
PUBLIC_MINIO_API_PORT=10000
PUBLIC_MINIO_DASHBOARD_PORT=9001
MINIO_ENDPOINT=http://localhost:10000
MINIO_PUBLIC_ENDPOINT=http://localhost:10000
MINIO_URL=http://localhost:10000

# RabbitMQ Configuration
RABBITMQ_USER=guest
RABBITMQ_PASS=guest

# Keycloak Configuration
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password

# Other Configuration
OPENAI_API_KEY=your-openai-api-key-here
EOF
		print_success "Created default .env file"
	fi
fi

# Validate .env file format
print_status "Validating .env file format..."
if grep -q "=" .env; then
	print_success ".env file format looks valid"
else
	print_error ".env file appears to be empty or malformed"
	exit 1
fi

# Load environment variables
print_status "Loading environment variables..."
if [ -f .env ]; then
	set -a
	. ./.env
	set +a
	QDRANT_COLLECTION_NAME="${QDRANT_COLLECTION_NAME:-illinois_chat}"
	QDRANT_VECTOR_SIZE="${QDRANT_VECTOR_SIZE:-4096}"
	print_success "Environment variables loaded"
else
	print_warning "No .env file found"
fi

ensure_local_app_envs

# Start Docker Compose services
print_status "Pulling Sim AI images..."
"${COMPOSE[@]}" pull simstudio sim-realtime sim-migrations

print_status "Starting Docker Compose services..."
"${COMPOSE[@]}" up -d

print_success "Docker Compose services started!"

wait_for_healthy() {
	local service="$1"
	local timeout="${2:-180}"
	local elapsed=0

	print_status "Waiting for ${service} to become healthy..."
	until "${COMPOSE[@]}" ps "$service" | grep -q "healthy"; do
		if [ "$elapsed" -ge "$timeout" ]; then
			print_error "✗ ${service} failed to become healthy"
			"${COMPOSE[@]}" logs "$service"
			exit 1
		fi
		sleep 3
		elapsed=$((elapsed + 3))
	done
	print_success "✓ ${service} is healthy"
}

wait_for_completed() {
	local service="$1"
	local timeout="${2:-240}"
	local elapsed=0

	print_status "Waiting for ${service} to complete..."
	while true; do
		local container_id state exit_code
		container_id="$("${COMPOSE[@]}" ps -aq "$service")"
		if [ -n "$container_id" ]; then
			state="$(docker inspect -f '{{.State.Status}}' "$container_id")"
			exit_code="$(docker inspect -f '{{.State.ExitCode}}' "$container_id")"
			if [ "$state" = "exited" ] && [ "$exit_code" = "0" ]; then
				print_success "✓ ${service} completed"
				return
			fi
			if [ "$state" = "exited" ]; then
				print_error "✗ ${service} exited with code ${exit_code}"
				"${COMPOSE[@]}" logs "$service"
				exit 1
			fi
		fi

		if [ "$elapsed" -ge "$timeout" ]; then
			print_error "✗ ${service} did not complete within ${timeout}s"
			"${COMPOSE[@]}" logs "$service"
			exit 1
		fi
		sleep 3
		elapsed=$((elapsed + 3))
	done
}

wait_for_healthy postgres-illinois-chat
wait_for_healthy postgres-keycloak
wait_for_healthy qdrant
wait_for_healthy minio
wait_for_healthy rabbitmq
wait_for_healthy keycloak 240
wait_for_healthy sim-db
wait_for_completed sim-migrations 300
wait_for_completed sim-keycloak-setup 180
wait_for_completed sim-sso-setup 180
wait_for_healthy sim-realtime
wait_for_healthy simstudio 300

print_success "All essential containers are running and healthy!"

# Initialize PostgreSQL schema (mandatory)
print_status "Initializing PostgreSQL schema..."

DB_NAME=${POSTGRES_DATABASE:-postgres}
DB_USER=${POSTGRES_USER:-${POSTGRES_USERNAME:-postgres}}

psql_main() {
	"${COMPOSE[@]}" exec -T postgres-illinois-chat psql -U "$DB_USER" -d "$DB_NAME" "$@"
}

print_status "Applying database schema from infra/db/migrations..."
if [ -f infra/db/migrations/20250328_remote_schema.sql ]; then
	print_status "Note: This Supabase schema dump will generate many non-critical errors for missing extensions/roles"
	psql_main -f - <infra/db/migrations/20250328_remote_schema.sql 2>/dev/null || {
		print_warning "Schema migration completed with some expected errors (Supabase-specific components)"
	}
	print_success "Core application tables created successfully"
else
	print_warning "infra/db/migrations/20250328_remote_schema.sql not found; skipping apply"
fi

print_status "Verifying PostgreSQL schema..."
# Helper to check table exists
check_table() {
	local tbl=$1
	exists=$(psql_main -tAc \
		"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='${tbl}')")
	if [ "$exists" = "t" ] || [ "$exists" = "true" ]; then
		print_success "✓ Table '${tbl}' exists"
		return 0
	else
		print_error "✗ Table '${tbl}' missing"
		return 1
	fi
}

# Helper to check function exists (by name only)
check_function() {
	local func=$1
	exists=$(psql_main -tAc \
		"SELECT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='${func}')")
	if [ "$exists" = "t" ] || [ "$exists" = "true" ]; then
		print_success "✓ Function '${func}' exists"
		return 0
	else
		print_error "✗ Function '${func}' missing"
		return 1
	fi
}

verify_ok=true
# Verify a minimal set that should exist after migrations
check_table documents || verify_ok=false
# Add more if desired; these are common in this project
check_table conversations || verify_ok=false
check_table messages || verify_ok=false

if [ "$verify_ok" != true ]; then
	print_error "Database schema verification failed. See errors above."
	exit 1
fi

print_success "PostgreSQL schema initialized and verified."

## Frontend schema alignment verification removed

# Populate Qdrant
print_status "Creating Qdrant collection..."

# Ensure QDRANT_URL is defined
if [[ -z $QDRANT_URL ]]; then
	QDRANT_URL="http://localhost:6333"
	print_warning "QDRANT_URL not set, using default: $QDRANT_URL"
fi

# If QDRANT_URL points to the container hostname, rewrite to localhost for host curl access
if echo "$QDRANT_URL" | grep -qE "http://qdrant(:6333)?$|http://qdrant:6333"; then
	print_warning "QDRANT_URL points to container hostname (qdrant). Using host-mapped URL instead."
	QDRANT_URL="http://localhost:6333"
fi

# Wait a bit more for Qdrant to be fully ready
print_status "Waiting for Qdrant to be fully ready..."
sleep 5

# Create Qdrant collection (with optional API key)
print_status "Creating Qdrant collection..."

# First, check if collection already exists
print_status "Checking if Qdrant collection exists..."
# Build headers (optionally include API key if provided)
CURL_HEADERS=("-H" "Content-Type: application/json")
if [[ -n $QDRANT_API_KEY ]]; then
	CURL_HEADERS+=("-H" "api-key: $QDRANT_API_KEY")
fi

if curl -s --max-time 10 "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" "${CURL_HEADERS[@]}" 2>/dev/null | grep -q '"status":"ok"'; then
	# Verify the existing collection schema matches expected config
	details=$(curl -sS --max-time 10 "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" "${CURL_HEADERS[@]}" 2>/dev/null || true)
	if echo "$details" | grep -q "\"size\"[[:space:]]*:[[:space:]]*${QDRANT_VECTOR_SIZE}" && echo "$details" | grep -q '"distance"[[:space:]]*:[[:space:]]*"Cosine"'; then
		print_success "✓ Qdrant collection already exists with correct schema (size=${QDRANT_VECTOR_SIZE}, distance=Cosine)"
	else
		print_warning "Existing Qdrant collection schema does not match expected. Recreating collection..."
		# Delete and recreate with correct schema
		delete_resp=$(curl -sS --max-time 10 -X DELETE "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" "${CURL_HEADERS[@]}" 2>/dev/null || true)
		print_status "Delete response: $delete_resp"
		create_resp=$(curl -sS --max-time 10 -X PUT "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" \
			"${CURL_HEADERS[@]}" \
			-d "{\"vectors\":{\"size\":${QDRANT_VECTOR_SIZE},\"distance\":\"Cosine\"}}" 2>/dev/null || true)
		if echo "$create_resp" | grep -q '"status":"ok"'; then
			print_success "✓ Qdrant collection recreated successfully with correct schema"
		else
			print_error "✗ Failed to recreate Qdrant collection"
			print_status "Create response: $create_resp"
			exit 1
		fi
	fi
else
	# Try multiple times to create the collection
	attempts=10
	success=false
	last_response=""
	for i in $(seq 1 $attempts); do
		print_status "Attempt $i/$attempts to create Qdrant collection..."
		response=$(curl -sS --max-time 10 -X PUT "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" \
			"${CURL_HEADERS[@]}" \
			-d "{\"vectors\":{\"size\":${QDRANT_VECTOR_SIZE},\"distance\":\"Cosine\"}}" 2>/dev/null || true)
		last_response="$response"

		if echo "$response" | grep -q '"status":"ok"'; then
			print_success "✓ Qdrant collection created successfully"
			success=true
			break
		elif echo "$response" | grep -qi "already exists"; then
			print_success "✓ Qdrant collection already exists"
			success=true
			break
		fi
		sleep 2
	done

	if [ "$success" != true ]; then
		print_error "✗ Failed to create Qdrant collection after $attempts attempts"
		print_status "Last response: $last_response"
		print_status "Checking Qdrant logs..."
		"${COMPOSE[@]}" logs qdrant
		exit 1
	fi
fi

print_success "Qdrant collection ready!"

# Initialize MinIO bucket
print_status "Setting up MinIO bucket..."

# Ensure MinIO environment variables are set
if [[ -z $AWS_ACCESS_KEY_ID ]]; then
	AWS_ACCESS_KEY_ID="minioadmin"
	print_warning "AWS_ACCESS_KEY_ID not set, using default: $AWS_ACCESS_KEY_ID"
fi

if [[ -z $AWS_SECRET_ACCESS_KEY ]]; then
	AWS_SECRET_ACCESS_KEY="minioadmin"
	print_warning "AWS_SECRET_ACCESS_KEY not set, using default: $AWS_SECRET_ACCESS_KEY"
fi

MINIO_CONTAINER="$("${COMPOSE[@]}" ps -q minio)"
if [ -n "$MINIO_CONTAINER" ]; then
	docker run --rm --entrypoint /bin/sh --network "container:${MINIO_CONTAINER}" minio/mc:RELEASE.2024-06-12T14-34-03Z \
		-c "mc alias set local http://localhost:${DOCKER_INTERNAL_MINIO_API_PORT:-10000} '${AWS_ACCESS_KEY_ID}' '${AWS_SECRET_ACCESS_KEY}' >/dev/null && mc mb -p local/uiuc-chat >/dev/null 2>&1 || true"
	print_success "✓ MinIO bucket 'uiuc-chat' is ready"
else
	print_warning "MinIO container was not found, skipping bucket setup"
fi

print_success "MinIO bucket setup complete!"

# Summary
echo ""
echo "=================================================="
print_success "Infrastructure setup complete!"
echo ""
echo "📋 Services are now running:"
echo "   - PostgreSQL (UIUC Chat): localhost:5432"
echo "   - PostgreSQL (Keycloak): localhost:5433"
echo "   - Redis: localhost:6379"
echo "   - Qdrant: localhost:6333"
echo "   - MinIO: localhost:${PUBLIC_MINIO_API_PORT:-10000}"
echo "   - MinIO Console: localhost:${PUBLIC_MINIO_DASHBOARD_PORT:-9001}"
echo "   - RabbitMQ: localhost:5672"
echo "   - RabbitMQ Management: localhost:15672"
echo "   - Keycloak: localhost:8080"
echo "   - Sim AI: localhost:${SIM_APP_PORT:-3010}"
echo "   - Sim realtime: localhost:${SIM_REALTIME_PORT:-3011}"
echo "   - Sim pgvector: localhost:${SIM_POSTGRES_PORT:-55432}"
echo ""
echo "📚 Development infrastructure ready:"
echo "   - Qdrant collection '${QDRANT_COLLECTION_NAME}' ready"
echo "   - MinIO bucket 'uiuc-chat' ready"
echo "   - All services healthy and ready"
echo ""
echo "🌐 Next steps:"
echo "1. Update hosted model/API keys in apps/backend/.env, apps/frontend/.env, and apps/crawlee/.env"
echo "2. Start the backend, worker, and frontend in separate terminals:"
echo "   cd apps/backend && flask --app ai_ta_backend.main:app --debug run --port 8000"
echo "   cd apps/backend && python ai_ta_backend/rabbitmq/worker.py"
echo "   cd apps/frontend && npm run local"
echo ""
echo "🔍 To verify everything is working:"
echo "   - Check containers: docker ps"
echo "   - Check logs: docker compose --project-directory . -f infra/docker/docker-compose.dev.yaml logs"
echo "   - Test Qdrant: curl -H 'api-key: ${QDRANT_API_KEY:-your-strong-key-here}' http://localhost:6333/collections"
echo "   - Test PostgreSQL: psql -h localhost -p 5432 -U postgres -d postgres"
