{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uiuc-chat.fullname" . }}-backend
  labels:
    {{- include "uiuc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uiuc-chat.backend.selectorLabels" . | nindent 4 }}
{{- end }}

