{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uiuc-chat.fullname" . }}-keycloak
  labels:
    {{- include "uiuc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uiuc-chat.keycloak.selectorLabels" . | nindent 4 }}
{{- end }}
