{{- if .Values.keycloak.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "uiuc-chat.fullname" . }}-keycloak-realm-setup
  labels:
    {{- include "uiuc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "uiuc-chat.labels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      restartPolicy: OnFailure
      containers:
      - name: realm-setup
        image: quay.io/keycloak/keycloak:17.0.1-legacy
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Keycloak to be ready..."
          until curl -f http://{{ include "uiuc-chat.fullname" . }}-keycl-http:80/auth/realms/master; do
            echo "Keycloak not ready yet, waiting..."
            sleep 10
          done
          
          echo "Keycloak is ready, waiting for admin user to be created..."
          
          # Wait for admin user to be created (can take some time with external database)
          for i in {1..30}; do
            echo "Attempt $i: Trying to configure admin credentials..."
            /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://{{ include "uiuc-chat.fullname" . }}-keycl-http:80/auth --realm master --user admin --password admin
            if [ $? -eq 0 ]; then
              echo "Admin credentials configured successfully!"
              break
            else
              echo "Admin user not ready yet, waiting 10 seconds..."
              sleep 10
            fi
          done
          
          if [ $? -eq 0 ]; then
            echo "Admin credentials configured, creating realm..."
            
            # Create the realm
            /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm=illinois_chat_realm -s displayName="UIUC.chat" -s enabled=true
            
            if [ $? -eq 0 ]; then
              echo "Realm created successfully!"
              
              # Create a client for the realm
              /opt/jboss/keycloak/bin/kcadm.sh create clients -r illinois_chat_realm -s clientId=uiuc-chat-client -s enabled=true -s publicClient=true -s standardFlowEnabled=true -s implicitFlowEnabled=true -s directAccessGrantsEnabled=true -s 'redirectUris=["*"]' -s 'webOrigins=["*"]'
              
              if [ $? -eq 0 ]; then
                echo "Client created successfully!"
              else
                echo "Failed to create client"
              fi
              
              # Create a test user
              /opt/jboss/keycloak/bin/kcadm.sh create users -r illinois_chat_realm -s username=testuser -s enabled=true -s email=test@example.com -s firstName=Test -s lastName=User
              
              if [ $? -eq 0 ]; then
                echo "Test user created successfully!"
                # Set password for the test user
                /opt/jboss/keycloak/bin/kcadm.sh set-password -r illinois_chat_realm --username testuser --new-password testpassword
                echo "Test user password set!"
              else
                echo "Failed to create test user"
              fi
              
            else
              echo "Failed to create realm"
              exit 1
            fi
          else
            echo "Failed to configure admin credentials"
            exit 1
          fi
          
          echo "Realm setup completed successfully!"
{{- end }}
