{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uiuc-chat.fullname" . }}-keycloak
  labels:
    {{- include "uiuc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      {{- include "uiuc-chat.keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uiuc-chat.keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uiuc-chat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: keycloak
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "uiuc-chat.image" .Values.keycloak.image }}
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start-dev
            - --http-enabled=true
            - --hostname=localhost
            - --hostname-strict=false
            - --db=postgres
            - --db-url=jdbc:postgresql://{{ include "uiuc-chat.postgresql.host" . }}:{{ include "uiuc-chat.postgresql.port" . }}/{{ include "uiuc-chat.postgresql.database" . }}
            - --db-username={{ include "uiuc-chat.postgresql.username" . }}
            - --db-password={{ .Values.secrets.postgresql.password }}
            {{- if .Values.keycloak.dbConfig.schema }}
            - --db-schema={{ .Values.keycloak.dbConfig.schema }}
            {{- end }}
            - --import-realm
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.env.KEYCLOAK_ADMIN | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uiuc-chat.fullname" . }}-secrets
                  key: keycloak-admin-password
            - name: KC_METRICS_ENABLED
              value: {{ .Values.keycloak.env.KC_METRICS_ENABLED | quote }}
            - name: KC_HEALTH_ENABLED
              value: {{ .Values.keycloak.env.KC_HEALTH_ENABLED | quote }}
          livenessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
