{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uiuc-chat.fullname" . }}-ollama
  labels:
    {{- include "uiuc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uiuc-chat.ollama.selectorLabels" . | nindent 4 }}
{{- end }}


