apiVersion: v1
kind: Service
metadata:
  name: uiuc-chat-backend
  namespace: uiuc-chat
  labels:
    app: uiuc-chat-backend
spec:
  selector:
    app: uiuc-chat-backend
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiuc-chat-backend
  namespace: uiuc-chat
  labels:
    app: uiuc-chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uiuc-chat-backend
  template:
    metadata:
      labels:
        app: uiuc-chat-backend
    spec:
      containers:
        - name: backend
          image: uiuc-chat-backend:helm-merge-3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 12
          startupProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 60
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: FLASK_ENV
              value: "development"
            - name: POSTGRES_HOST
              value: "uiuc-chat-postgresql"
            - name: POSTGRES_ENDPOINT
              value: "uiuc-chat-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_DATABASE
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: REDIS_URL
              value: "redis://:password@uiuc-chat-redis-master:6379/0"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@uiuc-chat-rabbitmq:5672/"
            - name: QDRANT_URL
              value: "http://uiuc-chat-qdrant:6333"
            - name: QDRANT_API_KEY
              value: ""
            - name: VYRIAD_QDRANT_URL
              value: "http://uiuc-chat-qdrant:6333"
            - name: VYRIAD_QDRANT_PORT
              value: "6333"
            - name: VYRIAD_QDRANT_API_KEY
              value: ""
            - name: MINIO_ENDPOINT
              value: "http://uiuc-chat-minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: S3_ENDPOINT
              value: "http://uiuc-chat-minio:9000"
            - name: S3_BUCKET_NAME
              value: "uiuc-chat-dev"
            - name: S3_USE_SSL
              value: "false"
            - name: OLLAMA_SERVER_URL
              value: "http://uiuc-chat-ollama:11434"
            - name: EMBEDDING_MODEL
              value: "nomic-embed-text"
            - name: NCSA_HOSTED_API_KEY
              value: ""
            - name: QDRANT_COLLECTION_NAME
              value: "illinois_chat_dev"
            # Missing environment variables for full functionality
            - name: KV_REST_API_TOKEN
              value: "dummy-token-for-testing"
            - name: EMAIL_SENDER
              value: "noreply@uiuc.chat"
            - name: VERCEL_READ_ONLY_API_KEY
              value: "dummy-vercel-key"
            - name: VERCEL_BASE_URL
              value: "https://api.vercel.com/v1/"
            # Supabase environment variables for PubMed extraction
            - name: SUPABASE_URL
              value: "https://dummy.supabase.co"
            - name: SUPABASE_API_KEY
              value: "dummy-supabase-key"

